- src/main/java/org/disq_bio/disq/impl/file/PathSplitSource.java
- src/main/java/org/disq_bio/disq/impl/formats/bam/BamSource.java
- src/main/java/org/disq_bio/disq/impl/formats/bgzf/BgzfBlockSource.java
- src/test/java/org/disq_bio/disq/HtsjdkReadsRddTest.java
- src/test/java/org/disq_bio/disq/impl/formats/bam/BamSourceTest.java
This reproduces the problem (#33) and provides a fix. It also adds log debugging to provide diagnostic information about splits and BGZF chunk boundaries to help with debugging issues like this in the future.
The bug occurs when a BGZF block boundary coincides with a split boundary. Here's a log file for a run using a file that produced an errant count:
```
10:49:42.990 DEBUG BamSource - PathChunk for partition 294: PathChunk{path=file:/home/tom/bamaftersparksortsize.bam, span=9865016001:489-9898557440:65535}
10:49:43.239 DEBUG BamSource - PathChunk for partition 295: PathChunk{path=file:/home/tom/bamaftersparksortsize.bam, span=9898557440:190-9932111872:65535}
```
From the log we see that the spans for the two paths overlap, since the first ends at 9898557440:65535 which is *after* …
> [DISQ-33] Duplicate reads bug

- CONTRIBUTORS.md
- LICENSE
- LICENSE_header.txt
> [DISQ-8] Add license header, empty CONTRIBUTORS.md file.

- CONTRIBUTING.md
- SUPPORT.md
> [DISQ-6] Add CONTRIBUTING and SUPPORT files.

- .travis.yml
- Speed-up travis builds
- Allows to test OpenJDK builds
Closes #22
> [DISQ-22] Add openjdk and cache to travis configuration

- pom.xml
- src/main/java/org/disq_bio/disq/serializer/DisqKryoRegistrator.java
This bump to Spark version 2.3.2 feels pretty safe.  We've run into some runtime conflicts between Parquet and Avro dependency versions present in Spark 2.3.2 but I don't believe we'll hit those here.
The bump to Spark 2.4.0 will allow us to provide both Scala 2.11 and Scala 2.12 versions of our dependencies, and given that work towards Spark 3.0 is happening on git head, we should start thinking on how we'll handle cross-building for Spark 2.x and 3.x.
We are set up for cross-building across multiple Scala and Spark versions in ADAM, but it is a bit of a mess, so I'm willing to entertain other forms of build wizardry here.
> Update Spark dependency version to 2.3.2.

- src/main/java/org/disq_bio/disq/impl/formats/cram/CramOutputFormat.java
- src/main/java/org/disq_bio/disq/impl/formats/cram/CramReferenceSourceBuilder.java
- src/main/java/org/disq_bio/disq/impl/formats/cram/CramSink.java
- src/main/java/org/disq_bio/disq/impl/formats/sam/AbstractSamSource.java
- src/main/java/org/disq_bio/disq/impl/formats/sam/AnySamOutputFormat.java
- src/main/java/org/disq_bio/disq/impl/formats/sam/AnySamSinkMultiple.java
When the CRAM reference is on GCS, writing will fail with a Kryo exception.
This change fixes this by not broadcasting the ReferenceSource.
This is hard to write a unit test for since it needs a GCS bucket to write to, however I have successfully tested it manually.
> CRAM ReferenceSource is not always broadcastable.

- pom.xml
- src/test/resources/simplelogger.properties
Attempts to silence upstream logging in unit test logs by using `slf4j-simple` logging implementation for test scope.  Won't fully be able to achieve this until https://github.com/samtools/htsjdk/pull/1262 is merged.
> Use slf4j-simple logging implementation for unit tests.

- src/main/java/org/disq_bio/disq/impl/file/FileSystemWrapper.java
- src/main/java/org/disq_bio/disq/impl/file/HadoopFileSystemWrapper.java
- src/main/java/org/disq_bio/disq/impl/file/Merger.java
- src/main/java/org/disq_bio/disq/impl/file/NioFileSystemWrapper.java
- src/main/java/org/disq_bio/disq/impl/formats/bam/BamSink.java
- src/main/java/org/disq_bio/disq/impl/formats/cram/CramSink.java
- src/main/java/org/disq_bio/disq/impl/formats/cram/CramSource.java
- src/main/java/org/disq_bio/disq/impl/formats/sam/SamSink.java
- src/main/java/org/disq_bio/disq/impl/formats/vcf/VcfSink.java
- src/test/java/org/disq_bio/disq/impl/file/MergerTest.java
This saves many calls to the file system when merging part files. On the local filesystem, and even HDFS, the current behaviour is not noticeable, but when running on GCS with large numbers of files the overhead is significant. (E.g. it took around 1 min to list the file sizes for ~1800 files. With this patch the time was reduced to around 2 seconds.)
Also, pass the current FileSystemWrapper to the Merger, rather than creating a new
instance. (Fixes #65)
> Add a method to FileSystemWrapper to get file lengths when doing a directory listing

- src/main/java/org/disq_bio/disq/serializer/DisqKryoRegistrator.java
Fixes #43.
Looks to me like this should be safe, but I haven't tried running on a cluster yet.
> [DISQ-43] Create new instances of file system wrappers instead of serialization with Kryo.

- src/htsjdk/java/htsjdk/samtools/BAMIndexMerger.java
- src/htsjdk/java/htsjdk/samtools/IndexMerger.java
- src/htsjdk/java/htsjdk/samtools/SBIIndexMerger.java
- src/htsjdk/java/htsjdk/tribble/index/tabix/TabixIndexMerger.java
- src/main/java/org/disq_bio/disq/impl/file/BaiMerger.java
- src/main/java/org/disq_bio/disq/impl/file/IndexFileMerger.java
- src/main/java/org/disq_bio/disq/impl/file/SbiMerger.java
- src/main/java/org/disq_bio/disq/impl/file/TbiMerger.java
- src/main/java/org/disq_bio/disq/impl/formats/bam/BamSink.java
- src/main/java/org/disq_bio/disq/impl/formats/vcf/VcfSink.java
When running on cloud storage I observed that it takes a while to merge the index parts (for .bai and .tbi files). The reason is that each part file is read sequentially, which can take a while due to cloud latency. By pipelining the reads the time to merge was reduced from ~10 minutes to ~1 minute (for an exome index).
This PR makes the changes to allow `BAMIndexMerger` and `TabixIndexMerger` to be given a part file one at a time (`SBIIndexMerger` already does this, so the three are being made more consistent). There are also corresponding changes in `BaiMerger` and `TbiMerger`.
> Merge indexes in a streaming fashion

- pom.xml
- src/htsjdk/java/htsjdk/samtools/BAMIndexer2.java
- src/main/java/org/disq_bio/disq/impl/formats/cram/CramSource.java
The changes to CRAM have introduced an incompatible change to CRAIEntry that affects CramSource in Disq. See the note about incompatible CRAM changes
at https://github.com/samtools/htsjdk/releases/tag/2.17.0.
This commit uses the new CRAIEntry API introduced in https://github.com/samtools/htsjdk/pull/1256
Note: the change has not been released yet (so this PR will fail to compile), but a new htsjdk release is imminent, so the Disq 0.2.0 release should wait for it.
> Upgrade to htsjdk 2.19.0

- pom.xml
- src/main/java/org/disq_bio/disq/impl/formats/bam/HeaderlessBamOutputFormat.java
- src/main/java/org/disq_bio/disq/impl/formats/bgzf/BGZFCompressionOutputStream.java
- src/main/java/org/disq_bio/disq/impl/formats/bgzf/TerminatorlessBlockCompressedOutputStream.java
- src/main/java/org/disq_bio/disq/impl/formats/vcf/HeaderlessVcfOutputFormat.java
- src/main/java/org/disq_bio/disq/impl/formats/vcf/VcfOutputFormat.java
- src/main/java/org/disq_bio/disq/impl/formats/vcf/VcfSink.java
- src/test/java/org/disq_bio/disq/AnySamTestUtil.java
- src/test/java/org/disq_bio/disq/BaseTest.java
- src/test/java/org/disq_bio/disq/BcftoolsTestUtil.java
- src/test/java/org/disq_bio/disq/HdfsTestUtil.java
- src/test/java/org/disq_bio/disq/HtsjdkReadsRddHdfsTest.java
- src/test/java/org/disq_bio/disq/HtsjdkReadsRddTest.java
- src/test/java/org/disq_bio/disq/SamtoolsTestUtil.java
- src/test/java/org/disq_bio/disq/impl/file/MergerTest.java
Currently only the tests in `MergerTest` are run against an HDFS minicluster (as the name suggests, an HDFS cluster that runs in the same JVM, used for testing). This change enables all the tests in `HtsjdkReadsRddTest` to run against HDFS, in addition to the local file system (as they do currently).
To enable this, some refactoring to use `java.nio.file.Path` instead of `java.io.File` was needed.
> Run read tests on HDFS minicluster

- .travis.yml
- src/build/bin/checkout-gatk-large-files.sh
- src/main/java/org/disq_bio/disq/serializer/DisqKryoRegistrator.java
This addresses #23 by running `RealWorldFilesIT` against all the GATK large files that are >1MB in size. This includes BAM, CRAM, and VCF.
> Test large files on Travis

- src/main/java/org/disq_bio/disq/impl/file/HadoopFileSystemWrapper.java
* Reducing the "Concat not supported, merging serially" message from a warning to an info level statement.
This message will occur on every run on certain file systems and is generally not a cause for alarm.
> Reduce warning to info on unsuported concat operation.

- pom.xml
A small build change to make it easier to test different versions of Spark and Scala. See #66
> Parameterize Scala version

- src/htsjdk/java/htsjdk/samtools/BAMIndexMerger.java
- src/htsjdk/java/htsjdk/samtools/CachingBAMFileIndexOptimized.java
- src/htsjdk/java/htsjdk/tribble/index/tabix/TabixIndexMerger.java
- src/test/java/org/disq_bio/disq/BaiMergingTest.java
Merging indexes for a large hg38 BAM file fails with OOM. On the face of it, this is odd since the indexes themselves are all quite small (each well under 1MB), even though there are a lot of them (~1000). However, hg38 has an unusually large number of reference sequences, ~3000 rather than the more usual ~30, and this causes the blowup in memory use.
There are ~3000 ref sequences, and ~1000 parts (and therefore bai files to merge). Calling `AbstractBAMFileIndex#query` creates an array of Bins of size ~4000. The way the bai merging works is that it calls `query` for every reference of every part then combines them at the end. So that's ~10^10 elements stored in memory!
This can be fixed by changing the order of combining. Store all the parts in memory, then combine reference-wise at the …
> BAI merge for hg38 fails with OOM

- .travis.yml
- pom.xml
- src/build/conf/spotbugs-exclude.xml
This change runs all the tests on Travis using Java 11 (in addition to the existing Java 8 tests).
> Test on Java 11

- .travis.yml
... and we already have openjdk8 to test Java 8
> Drop oraclejdk8 on travis since it is no longer supported

- src/main/java/org/disq_bio/disq/impl/formats/bam/BamSource.java
* We were querying the SBI index, throwing those results away, and then split-guessing.
* Now the sbi results are used if they are available.
* Fixes https://github.com/disq-bio/disq/issues/123
@wangdy12 I believe this fixes the problem.  I'm shocked we never noticed that before, but I guess I always run with verbosity higher than debug.
> Use results from SBI index instead of ignoring them

- src/test/java/org/disq_bio/disq/BcftoolsTestUtil.java
- src/test/java/org/disq_bio/disq/BcftoolsTestUtilTest.java
- src/test/resources/testEmpty.vcf
* Fixes https://github.com/disq-bio/disq/issues/132
* There was a bug in BcftoolsTestUtil which counted empty vcfs as having 1 record.
An empty vcf was added to the GATK test files which we test against which then caused our tests to fail.
This fixes the problem by correctly counting empty vcfs as having 0 records when testing with Bcftools.
> Fixing RealWorldFilesIT (#132)

- pom.xml
- src/main/java/org/disq_bio/disq/impl/formats/cram/CramSink.java
- src/main/java/org/disq_bio/disq/impl/formats/cram/CramSource.java
These changes depend on, and will be required for the next release of htsjdk, which will have some CRAM changes.
> Update for htsjdk CRAM changes.

- .travis.yml
- pom.xml
- src/main/java/org/disq_bio/disq/impl/file/HadoopFileSystemWrapper.java
- src/test/java/org/disq_bio/disq/BaseTest.java
- src/test/java/org/disq_bio/disq/impl/file/MergerTest.java
Fixes #130, fixes #142 
@heuermh Can you weigh in on this?  I needed to make a weird change to use the RawLocalFileSystem in order to avoid a checksum issue.   I'm not sure why we're getting the checksum failure though.  I suspect it's not getting recomputed correctly after some operation but I don't know why.
If I don't force it to use the raw filesystem we get 
```
htsjdk.samtools.util.RuntimeIOException: org.apache.hadoop.fs.ChecksumException: Checksum error: file:/var/folders/q3/hw5cxmn52wq347lg7rb_mzlw0000gq/T/test1179670579977857255.vcf at 0
at htsjdk.tribble.readers.AsciiLineReaderIterator$TupleIterator.advance(AsciiLineReaderIterator.java:88)
at htsjdk.tribble.readers.AsciiLineReaderIterator$TupleIterator.advance(AsciiLineReaderIterator.java:75)
at …
```
> Updating to spark 3.0.1 and hadoop 3.2.1

- pom.xml
- src/main/java/org/disq_bio/disq/impl/formats/vcf/VcfSink.java
Fixes #148 
While testing other dependency updates, I found that kryo-serializers (#146), google-cloud-nio (#145), fmt-maven-plugin (#149), and maven-failsafe-plugin (#150) cannot be updated without further changes.
> [DISQ-148] Update htsjdk dependency version to 2.23.0

- .github/workflows/ci.yml
- src/test/java/org/disq_bio/disq/AnySamTestUtil.java
- src/test/java/org/disq_bio/disq/HtsjdkReadsRddTest.java
Fixes for format errors reported by fmt-maven-plugin
```
[INFO] --- fmt-maven-plugin:2.9:check (default) @ disq ---
[INFO] Processed 91 files (2 non-complying).
[ERROR] Found 2 non-complying files, failing build
[ERROR] To fix formatting errors, run "mvn com.coveo:fmt-maven-plugin:format"
[ERROR] Non complying file: /Users/heuermh/working/disq/src/test/java/org/disq_bio/disq/AnySamTestUtil.java
[ERROR] Non complying file: /Users/heuermh/working/disq/src/test/java/org/disq_bio/disq/HtsjdkReadsRddTest.java
```
> Fix format errors reported by fmt-maven-plugin

- pom.xml
- src/main/java/org/disq_bio/disq/serializer/DisqKryoRegistrator.java
Note that this change may have ramifications for downstream projects due to the change of the `Allele` class to an interface, with `SimpleAllele` as the concrete replacement.
> Update to htsjdk 3.0, change Allele->SimpleAllele.
